<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 4.1.2 Linear Regression

## Prediction of House Price Using Linear Regression

### Data

The Sacramento real estate transactions file is a list of 985 real estate transactions in the Sacramento area reported over a five-day period, as reported by the Sacramento Bee.

In [1]:
import pandas as pd
import numpy as np
import pandas as pd

%matplotlib inline

### 1. Explore Data

Perform EDA on this dataset. Find Dependent and Independent Variables to predict house price.

In [2]:
# Read CSV
house_csv = "/Users/ayano/Desktop/Data Science & AI/csv/Sacramento_transactions.csv"

In [3]:
data = pd.read_csv(house_csv)

In [4]:
data.shape

(985, 12)

In [5]:
data.head()

street        city    zip state  beds  baths  sq__ft  \
0      3526 HIGH ST  SACRAMENTO  95838    CA     2      1     836   
1       51 OMAHA CT  SACRAMENTO  95823    CA     3      1    1167   
2    2796 BRANCH ST  SACRAMENTO  95815    CA     2      1     796   
3  2805 JANETTE WAY  SACRAMENTO  95815    CA     2      1     852   
4   6001 MCMAHON DR  SACRAMENTO  95824    CA     2      1     797   

          type                     sale_date  price   latitude   longitude  
0  Residential  Wed May 21 00:00:00 EDT 2008  59222  38.631913 -121.434879  
1  Residential  Wed May 21 00:00:00 EDT 2008  68212  38.478902 -121.431028  
2  Residential  Wed May 21 00:00:00 EDT 2008  68880  38.618305 -121.443839  
3  Residential  Wed May 21 00:00:00 EDT 2008  69307  38.616835 -121.439146  
4  Residential  Wed May 21 00:00:00 EDT 2008  81900  38.519470 -121.435768

In [6]:
data.tail()

street             city    zip state  beds  baths  sq__ft  \
980   9169 GARLINGTON CT       SACRAMENTO  95829    CA     4      3    2280   
981      6932 RUSKUT WAY       SACRAMENTO  95823    CA     3      2    1477   
982    7933 DAFFODIL WAY   CITRUS HEIGHTS  95610    CA     3      2    1216   
983     8304 RED FOX WAY        ELK GROVE  95758    CA     4      2    1685   
984  3882 YELLOWSTONE LN  EL DORADO HILLS  95762    CA     3      2    1362   

            type                     sale_date   price   latitude   longitude  
980  Residential  Thu May 15 00:00:00 EDT 2008  232425  38.457679 -121.359620  
981  Residential  Thu May 15 00:00:00 EDT 2008  234000  38.499893 -121.458890  
982  Residential  Thu May 15 00:00:00 EDT 2008  235000  38.708824 -121.256803  
983  Residential  Thu May 15 00:00:00 EDT 2008  235301  38.417000 -121.397424  
984  Residential  Thu May 15 00:00:00 EDT 2008  235738  38.655245 -121.075915

In [7]:
data.describe().T

count           mean            std           min            25%  \
zip        985.0   95750.697462      85.176072  95603.000000   95660.000000   
beds       985.0       2.911675       1.307932      0.000000       2.000000   
baths      985.0       1.776650       0.895371      0.000000       1.000000   
sq__ft     985.0    1314.916751     853.048243      0.000000     952.000000   
price      985.0  234144.263959  138365.839085   1551.000000  145000.000000   
latitude   985.0      38.607732       0.145433     38.241514      38.482717   
longitude  985.0    -121.355982       0.138278   -121.551704    -121.446127   

                     50%            75%            max  
zip         95762.000000   95828.000000   95864.000000  
beds            3.000000       4.000000       8.000000  
baths           2.000000       2.000000       5.000000  
sq__ft       1304.000000    1718.000000    5822.000000  
price      213750.000000  300000.000000  884790.000000  
latitude       38.626582      38.695589      39.020808  
longitude    -121.376220    -121.295778    -120.597599

In [8]:
data.isnull().sum()

street       0
city         0
zip          0
state        0
beds         0
baths        0
sq__ft       0
type         0
sale_date    0
price        0
latitude     0
longitude    0
dtype: int64

In [9]:
data.columns

Index(['street', 'city', 'zip', 'state', 'beds', 'baths', 'sq__ft', 'type',
       'sale_date', 'price', 'latitude', 'longitude'],
      dtype='object')

In [10]:
data[[#'street', #'city', #'zip', #'state',
    'beds', 'baths', 'sq__ft', 
    #'type', #'sale_date', 
    'price', 'latitude', 'longitude']]

beds  baths  sq__ft   price   latitude   longitude
0       2      1     836   59222  38.631913 -121.434879
1       3      1    1167   68212  38.478902 -121.431028
2       2      1     796   68880  38.618305 -121.443839
3       2      1     852   69307  38.616835 -121.439146
4       2      1     797   81900  38.519470 -121.435768
..    ...    ...     ...     ...        ...         ...
980     4      3    2280  232425  38.457679 -121.359620
981     3      2    1477  234000  38.499893 -121.458890
982     3      2    1216  235000  38.708824 -121.256803
983     4      2    1685  235301  38.417000 -121.397424
984     3      2    1362  235738  38.655245 -121.075915

[985 rows x 6 columns]

### 2. Predict Price

We are going to predict `price` from available information.

#### 2.1 What is the Target Variable? Why?

In [12]:
# ANSWER

y = data["price"]

#### 2.2 List all possible variables which might be Independent/Predictor variable.

In [13]:
# ANSWER

#beds
#baths
#sq_ft
#type

#### 2.3 Find correlation between variables

Find correlation between variables. Which is the best predictor? Why? State your reason.

In [14]:
# ANSWER

data.corr()

/var/folders/0z/jn67d04d61x09rscj406r8zr0000gn/T/ipykernel_59184/3471073009.py:3: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.corr()


zip      beds     baths    sq__ft     price  latitude  \
zip        1.000000  0.125319  0.069165  0.130108 -0.093353 -0.290389   
beds       0.125319  1.000000  0.839650  0.684041  0.342024 -0.291307   
baths      0.069165  0.839650  1.000000  0.665690  0.416208 -0.235792   
sq__ft     0.130108  0.684041  0.665690  1.000000  0.333897 -0.383274   
price     -0.093353  0.342024  0.416208  0.333897  1.000000 -0.039573   
latitude  -0.290389 -0.291307 -0.235792 -0.383274 -0.039573  1.000000   
longitude -0.539904 -0.053993  0.016582 -0.177742  0.284485  0.387925   

           longitude  
zip        -0.539904  
beds       -0.053993  
baths       0.016582  
sq__ft     -0.177742  
price       0.284485  
latitude    0.387925  
longitude   1.000000

#### 2.4 Find Coefficient and Intercept using Linear Regression

Using LinearRegression of sklearn.linear_model package find Coefficient and Intercept.

Create an instance of LinearRegression.

Explore following methods:

- fit
- predict
- score

In [15]:
from sklearn.linear_model import LinearRegression

##### 2.4.1 Fit predictor and target variables using linear regression 

In [16]:
# ANSWER

X = data['sq__ft'].values.reshape(-1,1)
y = data['price']

linreg = LinearRegression()
linreg.fit(X,y)

print(linreg.coef_, linreg.intercept_)

[54.15863969] 162930.16140699777


##### 2.4.2 Find R Score

Find $R^2$ Using ```score``` method of Linear Regression.

In [17]:
# ANSWER

linreg.score(X, y)

0.11148717682951437

### 3. Splitting Data

In [18]:
from sklearn.model_selection import train_test_split

#### 3.1 Create training and testing subsets

Hint: Using `train_test_split` Library.

```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
```

In [19]:
# ANSWER
## Create training and testing subsets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

#### 3.2 Check Shape, Sample of Test Train Data

In [22]:
# ANSWER
## Check training/test data

# About training
print('X_train is a %s' % type(X_train))
print('X_train has %d rows', X_train.shape[0])
print('')
print('Sample of X_train%s' % ('_'*50))
print(X_train[:10])

print('')
print('y_train is a %s' % type(y_train))
print('y_train has %d rows', y_train.shape)
print('')
print('Sample of y_train%s' % ('_'*50))
print(y_train[:10])

X_train is a <class 'numpy.ndarray'>
X_train has %d rows 659

Sample of X_train__________________________________________________
[[1758]
 [1643]
 [2354]
 [   0]
 [1354]
 [   0]
 [ 958]
 [1232]
 [ 888]
 [1440]]

y_train is a <class 'pandas.core.series.Series'>
y_train has %d rows (659,)

Sample of y_train__________________________________________________
433    217500
172     99000
125    335750
541    488750
879    104000
888    119000
90     244960
924    170000
181    125000
274    292000
Name: price, dtype: int64


In [23]:
# About test
print('X_train is a %s' % type(X_test))
print('X_train has %d rows', X_test.shape)
print('')
print('Sample of X_train%s' % ('_'*50))
print(X_test[:10])

print('')
print('y_train is a %s' % type(y_test))
print('y_train has %d rows', y_test.shape)
print('')
print('Sample of y_train%s' % ('_'*50))
print(y_test[:10])

X_train is a <class 'numpy.ndarray'>
X_train has %d rows (326, 1)

Sample of X_train__________________________________________________
[[ 906]
 [2382]
 [1962]
 [1739]
 [1527]
 [   0]
 [   0]
 [1900]
 [   0]
 [   0]]

y_train is a <class 'pandas.core.series.Series'>
y_train has %d rows (326,)

Sample of y_train__________________________________________________
613     77000
451    236000
731    240971
436    221000
275    293993
582      4897
707    215000
299    361745
718    222500
494    307000
Name: price, dtype: int64


#### 3.3 Using Linear Regression Find The Score

1. Fit model using X_train, y_train
2. Find score using X_test, y_test

In [24]:
# ANSWER

linreg = LinearRegression()
linreg.fit(X_train, y_train)

print(linreg.coef_, linreg.intercept_)

[47.43508406] 166482.34144968857


In [25]:
# ANSWER

linreg.score(X_test, y_test)

0.13602012247180006

### 4. Predict House Price

Let's assume we have information of following house:

- street:	1140 EDMONTON DR
- city:	SACRAMENTO
- zip:	95833
- state:	CA
- beds:	3
- baths:	2
- sq__ft:	1204
- type:	Residential

**Predict the price of this house using linear regression model.**

In [26]:
# ANSWER

linreg.intercept_, linreg.coef_

(166482.34144968857, array([47.43508406]))

In [27]:
# ANSWER
beta0 = linreg.intercept_
beta1 = linreg.coef_
x = 1204

Ypred = beta1 * x + beta0
print('Predicted house price: ', Ypred[0])

Predicted house price:  223594.18266380776


In [28]:
# ANSWER
x = [[1204]]
Ypred = linreg.predict(x)
print('Predicted house price: ', Ypred[0])

Predicted house price:  223594.18266380776


#### Find the error

In [29]:
# Predict price from X_test

y_preds = linreg.predict(X_test)

y_preds[:10]

array([209458.52761247, 279472.71169224, 259549.97638499, 248971.95263852,
       238915.71481676, 166482.34144969, 166482.34144969, 256609.00117297,
       166482.34144969, 166482.34144969])

In [30]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test, y_preds, squared=True)

18951801967.76203



---



---



> > > > > > > > > © 2023 Institute of Data


---



---



